### ISSUE TITLE
RiGrammar exec-mechanism broken in NodeJS

### ISSUE THREAD

**Issue by dhowe** [dhowe/RiTaJSHistory#9]
The exec mechanism isn't currently working in NodeJS...
Its not able to pass the scope of the callback function into Node's eval: 

  require("vm").runInThisContext(exec,context);

Currently 3 tests are skipped (conditionally for NodeJS) in RiGrammar-tests.js: 
  RiGrammar.exec1, RiGrammar.exec2, & RiGrammar.execArgs.

Any NodeJS experts know how to make this work?

(the Java version, using reflection, should also demonstrate the correct semantics...)

**Comment by ruohoruotsi** [comment]
Hi Daniel,
does this mean that callbacks are not supported in Javascript per
http://rednoise.org/rita/reference/RiGrammar.html

I'm trying to figure out how to do:

`"<rule2>": "The cat ran after the `pluralize('cat')` | The \
     <noun> ran after the `pluralize(<noun>)`"`

but am getting errors and i noticed the link to this Issue. 

Is it closed because It-is-not-going-to-be-fixed? Or Is there a workaround??

I'm not a NodeJS expert, but I can be to get callbacks working, as I need this greatly for my webapp. Please assign this to me if so.

cheers,
rr

**Comment by dhowe** [comment]
Thanks RR, help is much appreciated. The problem (as noted above) is how to get the exec function (pluralize() in the case above) injected into the NodeJS context (the global context isn't available as it is in the browser's eval) . 
-DH

**Comment by dhowe** [comment]
Hey rr,
Any progress on this?
cheers (and happy new year!)
Daniel

**Comment by ruohoruotsi** [comment]
Hiya,
Happy new year!
No sorry, I've been (as well as wife & kids) really hit hard with the flu.
On the mend & will visit this shortly, as I'm trying to launch my music
critcism web app shortly.

Cheers,
rr

**Comment by dhowe** [comment]
moving to RiTa
